name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  style:
    name: Coding Style
    uses: ./.github/workflows/workflow-style.yaml
    secrets: inherit

  filter:
    needs: style
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'src/**'
            infra:
              - .github/**

  build:
    needs: filter
    name: Build & Test
    uses: ./.github/workflows/workflow-build.yaml
    permissions:
      contents: read
      pull-requests: write
    with:
      version: ${{ github.event.pull_request.number }}
      environment-name: Development
    secrets: inherit
