name: Build and Test Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "Version number (PR number)"
      environment-name:
        required: true
        type: string
        description: "Environment name for deployment"

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Comment PR with coverage info
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
